commit_message: '[ci skip]'
files:
  - source: /app/lib/l10n/app_en.arb
    translation: /app/lib/l10n/app_%osx_locale%.arb
  - source: /docs/i18n/en/**/*
    translation: /docs/i18n/%osx_locale%/**/%original_file_name%
  - source: /docs/docs/**/*
    translation: /docs/i18n/%osx_locale%/docusaurus-plugin-content-docs/current/**/%original_file_name%
  - source: /docs/community/**/*
    ignore_settings: 1
    ignore:
      - CHANGELOG.md
      - versions.md
    translation: /docs/i18n/%osx_locale%/docusaurus-plugin-content-docs-community/current/**/%original_file_name%
  - source: /docs/versioned_docs/**/*
    translation: /docs/i18n/%osx_locale%/docusaurus-plugin-content-docs/**/%original_file_name%
