blank_issues_enabled: false
contact_links:
  - name: Report iOS issue
    url: https://github.com/LinwoodDev/Butterfly/issues/244
    about: Please ask and answer questions here. Synced with discord.
  - name: Ask a question
    url: https://github.com/LinwoodDev/Butterfly/discussions
    about: Please ask and answer questions here. Synced with discord.
  - name: Linwood Matrix
    url: https://go.linwood.dev/discord
    about: Please ask and answer questions here. Synced with discord.
  - name: Linwood Discord
    url: https://go.linwood.dev/discord
    about: Please ask and answer questions here. Synced with matrix.
