name: butterfly_api
description: The Linwood Butterfly API
version: 2.0.0-alpha.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^2.0.1
  collection: ^1.17.1
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
dependency_overrides: 
  collection: 1.17.1
dev_dependencies:
  build_runner: ^2.3.3
  freezed: ^2.3.2
  lints: ^2.0.0
  test: ^1.21.0
