name: Flutter build

on: [push]

jobs:
  build-apk:
    runs-on: ubuntu-18.04
    steps:
      - name: ⬆️ Checkout
        uses: actions/checkout@v2
      - name: 🔧 Setup java
        uses: actions/setup-java@v2
        with:
          java-version: "8.x"
          distribution: "adopt"
      - uses: subosito/flutter-action@v1
        with:
          channel: "beta" # or: 'stable' or 'dev'
      - name: 📦 Get dependencies
        run: |
          cd app
          flutter pub get
      #- run: flutter test
      - name: 🏭 Build
        run: |
          cd app
          flutter doctor -v
          flutter build apk -v --release
      - name: Archive
        uses: actions/upload-artifact@v2
        with:
          name: apk-build
          path: app/build/app/outputs/flutter-apk/app-release.apk
  build-windows:
    runs-on: windows-latest
    steps:
      - name: ⬆️ Checkout
        uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: "beta" # or: 'stable' or 'dev'
      - name: ✅ Enable platforms
        run: flutter config --enable-windows-desktop
      - name: 📦 Get dependencies
        run: |
          cd app
          flutter pub get
      - name: 🏭 Build
        shell: cmd
        run: |
          cd app
          flutter clean
          flutter doctor -v
          flutter build windows -v --release
          "/c/Program Files (x86)/Inno Setup 6/ISCC.exe" -MyAppVersion=${version}_${buildnumber} ButterflySetup.iss
        # flutter pub run msix:create
      - name: Archive
        uses: actions/upload-artifact@v2
        with:
          name: windows-build
          path: |
            app/build/windows/runner/Release/**
  build-linux:
    runs-on: ubuntu-18.04
    steps:
      - name: ⬆️ Checkout
        uses: actions/checkout@v2
      - name: Get dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libx11-dev pkg-config cmake ninja-build libblkid-dev liblzma-dev
      - uses: subosito/flutter-action@v1
        with:
          channel: "dev" # or: 'stable' or 'dev'
      - name: ✅ Enable platforms
        run: flutter config --enable-linux-desktop
      - name: 📦 Get dependencies
        run: |
          cd app
          flutter pub get
      - name: 🏭 Build
        run: |
          cd app
          flutter clean
          flutter doctor -v
          flutter build linux -v --release
      - name: Archive
        uses: actions/upload-artifact@v2
        with:
          name: linux-build
          path: |
            app/build/linux/x64/release/bundle/**
  #build-macos:
  #  runs-on: macos-latest
  #  steps:
  #    - name: ⬆️ Checkout
  #      uses: actions/checkout@v2
  #    - uses: subosito/flutter-action@v1
  #      with:
  #        channel: "dev" # or: 'stable' or 'dev'
  #    - name: ✅ Enable platforms
  #      run: flutter config --enable-macos-desktop
  #    - name: 📦 Get dependencies
  #      run: |
  #        flutter pub get
  #    - name: 🏭 Build
  #      run: |
  #        flutter clean
  #        flutter doctor -v
  #        flutter build macos -v
  #    - name: Archive
  #      uses: actions/upload-artifact@v2
  #      with:
  #        name: macos-build
  #        path: |
  #          build/windows/runner/Release/**
  deploy:
    runs-on: ubuntu-18.04
    needs:
      - build-apk
      - build-windows
      - build-linux
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: apk-build
      - uses: actions/download-artifact@v2
        with:
          name: windows-build
          path: windows-build/
      - uses: actions/download-artifact@v2
        with:
          name: linux-build
          path: linux-build/
      - name: 📦 Zip artifacts
        run: |
          zip -r windows.zip windows-build/*
          zip -r linux.zip linux-build/*
      - name: 🚀 Deploy release
        if: github.ref == 'refs/heads/main'
        uses: eine/tip@master
        continue-on-error: true
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          tag: "release"
          files: |
            Butterfly-Setup.exe
            app-release.apk
            windows.zip
            linux.zip
      - name: 🚀 Deploy preview
        if: github.ref == 'refs/heads/develop'
        uses: eine/tip@master
        continue-on-error: true
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          tag: "preview"
          files: |
            Butterfly-Setup.exe
            app-release.apk
            windows.zip
            linux.zip
      - name: Release
        uses: softprops/action-gh-release@v1
        continue-on-error: true
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          files: |
            Butterfly-Setup.exe
            app-release.apk
            windows.zip
            linux.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
