name: documentation

on:
  pull_request:
    branches: [develop]
  push:
    branches: [develop]

jobs:
  checks:
    if: github.event_name != 'push'
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile
      - name: Check lint
        run: |
          cd docs
          yarn lint
      - name: Test Build
        run: |
          cd docs
          yarn build
