name: Release

on:
  workflow_dispatch:
    branches:
      - develop
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: develop
          token: ${{ secrets.CI_PAT }}
      - name: Setup git
        id: setup
        run: |
          git config --global user.email "ci@linwood.dev"
          git config --global user.name "Linwood CI"
      - name: Update version
        shell: bash
        env:
          BUTTERFLY_VERSION: ${{ env.BUTTERFLY_VERSION }}
          CURRENT_CHANGELOG: ${{ env.CURRENT_CHANGELOG }}
          BUTTERFLY_RELEASE_DATE: ${{ env.BUTTERFLY_RELEASE_DATE }}
        run: |
          dart pub get -C tools
          dart run tools/set_version.dart 
          
          git add .
          git commit -m "Update Version to ${BUTTERFLY_VERSION}"
          git push origin develop
      - name: Merge develop into main
        run: |
          git checkout main
          git merge develop
          git push origin main
      - name: Create tag
        run: |
          BUTTERFLY_VERSION="${{ env.BUTTERFLY_VERSION }}"
          git tag -a v${BUTTERFLY_VERSION} -m "Release ${BUTTERFLY_VERSION}"
          git push origin v${BUTTERFLY_VERSION}
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.BUTTERFLY_VERSION }}
          name: v${{ env.BUTTERFLY_VERSION }}
          body_path: fastlane/metadata/android/en-US/changelogs/${{ env.BUTTERFLY_BUILD_NUMBER }}.txt
      - name: Rebase develop
        run: |
          git checkout develop
          git rebase main
          git push origin develop
      - name: Discord Webhook Action
        uses: tsickert/discord-webhook@v4.0.0
        with:
          webhook-url: ${{ secrets.WEBHOOK_URL }}
          content: |
            Version ${{ env.BUTTERFLY_VERSION }} released!
            Download it here: https://docs.butterfly.linwood.dev/downloads
            
            https://github.com/LinwoodCloud/butterfly/releases/tag/v${{ env.BUTTERFLY_VERSION }}




