name: Release

on:
  workflow_dispatch:
    branches:
      - develop
    inputs:
      changelog:
        type: string
        description: Changelog for the release
        required: true
jobs:
  rebase:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          git --version
          git config branch.autosetuprebase always
          git config --global user.email "actions@github.com"
          git config --global user.name "Actions"
          git pull --tags

          // Get current date time formatted in yyy-mm-dd
          BUTTERFLY_VERSION_REGEX="version:\s(.+)\+"
          [[ $(grep -E "${BUTTERFLY_VERSION_REGEX}" app/pubspec.yaml) =~ ${BUTTERFLY_VERSION_REGEX} ]]
          BUTTERFLY_VERSION=${BASH_REMATCH[1]}
          BUTTERFLY_RELEASE_DATE=$(date +%Y-%m-%d)
          INPUT_CHANGELOG="<!-- ENTER CHANGEOG HERE -->\n\n## ${BUTTERFLY_VERSION} (${BUTTERFLY_RELEASE_DATE})\n\n${ github.event.inputs.changelog }"
          sed -i "s/<\!-- ENTER CHANGELOG HERE -->/${INPUT_CHANGELOG}/g" docs/community/CHANGELOG.md
