name: Release

on:
  workflow_dispatch:
    branches:
      - develop
jobs:
  rebase:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: develop
      - name: Setup git
        id: setup
        run: |
          BUTTERFLY_VERSION_REGEX="version:\s(.+)\+(.+)"
          [[ $(grep -E "${BUTTERFLY_VERSION_REGEX}" app/pubspec.yaml) =~ ${BUTTERFLY_VERSION_REGEX} ]]
          echo "BUTTERFLY_VERSION=${BASH_REMATCH[1]}" >> $GITHUB_ENV
          echo "BUTTERFLY_BUILD_NUMBER=${BASH_REMATCH[2]}" >> $GITHUB_ENV
          echo "BUTTERFLY_RELEASE_DATE=$(date +%Y-%m-%d)" >> $GITHUB_ENV
          BUTTEFLY_VERSION=${{ env.BUTTERFLY_VERSION }}
          BUTTERFLY_RELEASE_DATE=${{ env.BUTTERFLY_RELEASE_DATE }}
          echo "CURRENT_CHANGELOG=$(cat fastlane/metadata/android/en-US/changelogs/${BUTTERFLY_BUILD_NUMBER}.txt)" >> $GITHUB_ENV
          CURRENT_CHANGELOG=${{ env.CURRENT_CHANGELOG }}
          echo "INPUT_CHANGELOG=\"<\!--ENTER CHANGELOG HERE-->\n\n## ${BUTTERFLY_VERSION} (${BUTTERFLY_RELEASE_DATE})\n\n${CURRENT_CHANGELOG}\"" >> $GITHUB_ENV
          git config --global user.email "actions@github.com"
          git config --global user.name "Actions"
      - name: Update changelog
        run: |
          INPUT_CHANGELOG="${{ env.INPUT_CHANGELOG }}"
          BUTTERFLY_VERSION="${{ env.BUTTERFLY_VERSION }}"
          sed -i "s/<\!--ENTER CHANGELOG HERE-->/${INPUT_CHANGELOG}/g" docs/community/CHANGELOG.md
          git add docs/community/CHANGELOG.md
          git commit -m "Update CHANGELOG.md for ${BUTTERFLY_VERSION}"
          git push origin develop
      - name: Merge develop into main
        run: |
          git checkout main
          git merge develop
          git push origin main
      - name: Create tag
        run: |
          BUTTERFLY_VERSION="${{ env.BUTTERFLY_VERSION }}"
          git tag -a v${BUTTERFLY_VERSION} -m "Release ${BUTTERFLY_VERSION}"
          git push origin v${env.BUTTERFLY_VERSION}
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.BUTTERFLY_VERSION }}
          name: v${{ env.BUTTERFLY_VERSION }}
          body: ${{ env.CURRENT_CHANGELOG }}



