name: Release

on:
  workflow_dispatch:
    branches:
      - develop
    inputs:
      release_version:
        default: '0.0.0'
        description: 'The version to release'
        required: true
      next_version:
        default: '0.0.0'
        description: 'The next version to be released'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: develop
          token: ${{ secrets.CI_PAT }}
      - uses: subosito/flutter-action@v1
        with:
          channel: 'beta' # or: 'stable' or 'dev'
      - name: Setup git
        id: setup
        run: |
          git config --global user.email "ci@linwood.dev"
          git config --global user.name "Linwood CI"
      - name: Update version
        run: |
          dart pub get -C tools
          dart run tools/set_version.dart ${{ github.event.inputs.release_version }} --build-number keep
          
          git add .
          git commit -m "Update version to ${{ github.event.inputs.release_version }}"
          git push origin develop
      - name: Merge develop into main
        run: |
          git checkout main
          git merge develop
          git push origin main
      - name: Create tag
        run: |
          BUTTERFLY_VERSION="${{ github.event.inputs.release_version }}"
          git tag -a v${{ github.event.inputs.release_version }} -m "Release ${BUTTERFLY_VERSION}"
          git push origin v${BUTTERFLY_VERSION}
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.event.inputs.release_version }}
          name: v${{ github.event.inputs.release_version }}
          body_path: fastlane/metadata/android/en-US/changelogs/${{ github.event.inputs.release_version }}.txt
      - name: Rebase develop
        run: |
          git checkout develop
          git rebase main
          git push origin develop
      - name: Set next version
        run: |
          dart pub get -C tools
          dart run tools/set_version.dart --build-number increment ${{ github.event.inputs.next_version }} --no-changelog
          git add .
          git commit -m "Update Version to ${{ github.event.inputs.next_version }}"
          git push origin develop
      - name: Discord Webhook Action
        uses: tsickert/discord-webhook@v4.0.0
        with:
          webhook-url: ${{ secrets.WEBHOOK_URL }}
          content: |
            Version ${{ github.event.inputs.release_version }} released!
            Download it here: https://docs.butterfly.linwood.dev/downloads
            
            https://github.com/LinwoodCloud/butterfly/releases/tag/v${{ github.event.inputs.release_version }}




