name: Publish to WinGet
on:
  workflow_run:
    workflows: ["Flutter build"]
    types:
      - completed
jobs:
  publish:
    runs-on: windows-latest
    if: startsWith(github.ref, "refs/tags/v")
    steps:
      - if: github.event.action == 'released'
        uses: vedantmgoyal2009/winget-releaser@latest
        with:
          identifier: LinwoodCloud.Butterfly
          token: ${{ secrets.CI_PAT }}
      - if: github.event.action == 'prereleased'
        uses: vedantmgoyal2009/winget-releaser@latest
        with:
          identifier: LinwoodCloud.Butterfly.Nightly
          version-regex: '(?<=v).*'
          token: ${{ secrets.CI_PAT }}
